# Generated by Django 2.2.4 on 2020-04-18 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='place',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Shop'),
            preserve_default=False,
        ),
    ]
