# Generated by Django 2.2.4 on 2020-04-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('Grocery Store', 'Grocery Store'), ('Meat Shop', 'Meat Shop'), ('Chicken Shop', 'Chicken Shop')], max_length=200),
        ),
    ]
