# Generated by Django 2.2.4 on 2020-04-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='being_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_requested',
        ),
        migrations.AddField(
            model_name='order',
            name='mode_of_payment',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Patt - Kadam', 'Patt - Kadam')], default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Not Accepted by Shop', 'Not Accepted by Shop'), ('Accepted by Shop', 'Accepted by Shop'), ('Under process', 'Under process'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
