# Generated by Django 2.2.4 on 2020-04-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200424_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_delivery_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_shop_owner',
            field=models.BooleanField(default=False),
        ),
    ]
