# Generated by Django 2.2.4 on 2020-04-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200424_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Shop'),
        ),
    ]
