# Generated by Django 2.2.4 on 2020-04-26 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Place'),
        ),
    ]
