# Generated by Django 2.2.4 on 2020-04-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_orderitem_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
