# Generated by Django 2.2.4 on 2020-05-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200521_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Cash on Delivery', 'Cash on Delivery'), ('Patt - Kadam', 'Patt - Kadam')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Accepted by Shop', 'Accepted by Shop'), ('Under process', 'Under process'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], default='Not Accepted by Shop', max_length=200, null=True),
        ),
    ]
