from django.urls import path
from .views import (
    UserIDView,
    UserTypeView,
    ItemListView,
    ItemDetailView,
    ShopListView,
    ShopProductListView,
    AddToCartView,
    OrderDetailView,
    OrderQuantityUpdateView,
    #     PaymentView,
    AddCouponView,
    CountryListView,
    AddressListView,
    AddressCreateView,
    AddressUpdateView,
    AddressDeleteView,
    OrderItemDeleteView,
    #     PaymentListView,
    OrderConfirmView,
    OrderListView,
    PlaceListView,
    PlaceShopListView,
    OrderDeleteView,
    AreaListView,
    orderAddressView,
    OrderStatusUpdateView
)

urlpatterns = [
    path('user-id/', UserIDView.as_view(), name='user-id'),
    path('user-type/', UserTypeView.as_view(), name='UserType'),
    path('countries/', CountryListView.as_view(), name='country-list'),
    path('addresses/', AddressListView.as_view(), name='address-list'),
    path('addresses/create/', AddressCreateView.as_view(), name='address-create'),
    path('addresses/<pk>/update/',
         AddressUpdateView.as_view(), name='address-update'),
    path('addresses/<pk>/delete/',
         AddressDeleteView.as_view(), name='address-delete'),
    path('addresses/<pk>/',
         orderAddressView.as_view(), name='order-address'),
    path('products/', ItemListView.as_view(), name='product-list'),
    path('products/<pk>/', ItemDetailView.as_view(), name='product-detail'),

    path('places/', PlaceListView.as_view(), name='place-list'),
    path('places/<int:place_id>/shops', PlaceShopListView.as_view(),
         name='place-shop-list'),
    path('places/<name>/areas', AreaListView.as_view(),
         name='area-list'),

    path('shops/', ShopListView.as_view(), name='shop-list'),
    path('shops/<int:shop_id>/products', ShopProductListView.as_view(),
         name='shop-product-list'),

    path('add-to-cart/', AddToCartView.as_view(), name='add-to-cart'),
    path('order-summary/', OrderDetailView.as_view(), name='order-summary'),
    #   path('checkout/', PaymentView.as_view(), name='checkout'),
    path('checkout/', OrderConfirmView.as_view(), name='checkout'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('order-items/<pk>/delete/',
         OrderItemDeleteView.as_view(), name='order-item-delete'),
    path('order-item/update-quantity/',
         OrderQuantityUpdateView.as_view(), name='order-item-update-quantity'),
    #     path('payments/', PaymentListView.as_view(), name='payment-list'),
    path('orders/', OrderListView.as_view(), name='order-list'),
    path('orders/<pk>/delete/',
         OrderDeleteView.as_view(), name='order-delete'),
    path('orders/<pk>/status-update/',
         OrderStatusUpdateView.as_view(), name='order-status-update'),


]
